export const COMENZAR_DESCARGA_NOTICIAS = "COMENZAR_DESCARGA_NOTICIAS";
export const DESCARGA_NOTICIAS_EXITO = "DESCARGA_NOTICIAS_EXITO";
export const DESCARGA_NOTICIAS_ERROR = "DESCARGA_NOTICIAS_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const LOGUEANDO_USUARIO = "LOGUEANDO_USUARIO";
export const REGISTRANDO_USUARIO = "REGISTRANDO_USUARIO";

export const USER_SUSCRIBED = "USER_SUSCRIBED";